### ISSUE TITLE
Address projects and open source

### ISSUE THREAD

**Issue by cheapwebmonkey** [civicdata/bylaws#5]
Specific section addressing projects being open sourced and which default license will be used, etc

**Comment by thebouv** [comment]
This is a very interesting topic.

Which projects are CDA projects?  For instance, just by attending a CDA hackathon doesn't make the project being worked on a CDA project.  So, what defines a CDA project?  Core members working on it?  "Official" designation as an adopted project.

I do not think we should try to say that every project that is worked on at a CDA event has to be open source, follow any particular license, or in fact even be affiliated with the CDA at all.

The CDA itself will have projects it champions and are "official" projects that can be covered by things like a default license, etc.

But I think part of this decision needs to be the discussion of what is and is not a CDA project.

**Comment by OrthoStice** [comment]
Just curious if this might also be more appropriately addressed in a program document than in bylaws?  (as per discussion about core membership)  I do think it's important we address for sure.

**Comment by cheapwebmonkey** [comment]
I agree with both of the comments above. A project made at a CDA event does not constitute a CDA project, however, a project made by CDA members at a CDA event, does, in my view, or any project that is designated by the creators as a CDA project, I'm fine with that as well.

I need to think longer about the bylaws, apparently, as I am still not sure where I land on that point.

**Comment by mgottholsen** [comment]
I think general guidance that there is a default license (MIT etc) that should be used if there are two or more members in the inception of a project, with a program document to @OrthoStice's point that provides alternatives. I think this would keep the work open by default, done by CDA.

**Comment by mgottholsen** [comment]
Closing this issue in favor of a separate document that details project governance, best practices and procedures. See PR #11 .
